# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_last_login'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_User_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='storeuserrelation',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storeuserrelation',
            name='user',
        ),
        migrations.DeleteModel(
            name='StoreUserRelation',
        ),
    ]
