# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Product_Category',
        ),
    ]
