# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180528_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product_Category'),
        ),
    ]
