# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180531_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='個', max_length=50),
        ),
    ]
