# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_last_login'),
        ('inventory', '0002_inventory_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_history',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='user.User'),
        ),
        migrations.AlterField(
            model_name='inventory_history',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='user.User'),
        ),
    ]
