# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180618_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_less_safety_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='safety_inventory_amount',
            field=models.IntegerField(default=0),
        ),
    ]
